### PR TITLE
Completed prep-javascript-functions

### PR DESCRIPTION
**Pull request by chang-yoo**
image

### CODE REVIEW

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Hi Changhyun, please be sure to include all of the functions listed in the assignment.

https://github.com/chang-yoo/prep-0222-code-solutions/pull/15/files

**Comment by chang-yoo** [comment]
hello Tim.
I've updated the work and please let me know if I can merge it.

Thanks!

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Hi Changhyun, please be sure to add, commit, and push your changes to this branch.

**Comment by chang-yoo** [comment]
> Hi Changhyun, please be sure to add, commit, and push your changes to this branch.

hi Tim, can you check one more time if it's okay to merge it?
I see all the works on the fils changed web and wondering if there is anything to be changed.

Thanks!

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
